language: python

python:
 - "2.7"

before_install:
 - sudo apt-get update
 - |
   sudo apt-get install -y \
   autoconf \
   automake \
   autotools-dev \
   curl \
   libmpc-dev \
   libmpfr-dev \
   libgmp-dev gawk \
   build-essential \
   bison \
   flex \
   texinfo \
   gperf \
   libtool \
   patchutils \
   bc \
   zlib1g-dev \
   libexpat-dev \
   realpath

install:
 # Install verilator
 - wget https://github.com/cornell-brg/verilator-travisci-cache/raw/master/verilator-travis-4.008.tar.gz
 - tar -C ${HOME} -xzf verilator-travis-4.008.tar.gz
 - export VERILATOR_ROOT=${HOME}/verilator
 - export PATH=${VERILATOR_ROOT}/bin:${PATH}
 - export PYMTL_VERILATOR_INCLUDE_DIR=${VERILATOR_ROOT}/share/verilator/include
 - verilator --version
 - pip install --upgrade pip
 - pip --version
 - pip install --upgrade pytest
 - pip install --upgrade yapf

before_script:
 - .travis/fetch-riscv-gnu-toolchain
 - export PATH="$TRAVIS_BUILD_DIR/riscv-gnu-toolchain/bin:$PATH"
 - tests/core/program/build-riscv-tests
 - pip install -e .[test]
 - mkdir -p build
 - cd build

script:
 - py.test ../tests/core/program_test.py::test_rtl_proc -k verilate -v
 - ../lizard/format --diff
