language: python

python:
 - "2.7"

before_install:
 - sudo apt-get update
 - |
   sudo apt-get install -y \
   autoconf \
   automake \
   autotools-dev \
   curl \
   libmpc-dev \
   libmpfr-dev \
   libgmp-dev gawk \
   build-essential \
   bison \
   flex \
   texinfo \
   gperf \
   libtool \
   patchutils \
   bc \
   zlib1g-dev \
   libexpat-dev \
   realpath

install:
 # Install verilator
 - git clone https://github.com/cornell-brg/verilator-travisci-cache.git
 - tar xfz verilator-travisci-cache/verilator-travis-3.876.tar.gz
 - export VERILATOR_ROOT=${PWD}/verilator-3.876
 - export PATH=${VERILATOR_ROOT}/bin:$PATH
 - export PYMTL_VERILATOR_INCLUDE_DIR=${VERILATOR_ROOT}/include
 - verilator --version
 - pip -q install git+https://github.com/cornell-brg/pymtl.git@jng55-closures
 - pip -q install git+https://github.com/wizard97/yapf.git
 - pip -q install futures
 - pip -q install hypothesis
 - pip -q install pytest-xdist
 - pip list --format=columns

before_script:
 - .travis/fetch-riscv-gnu-toolchain
 - export PATH="$TRAVIS_BUILD_DIR/riscv-gnu-toolchain/bin:$PATH"
 - src/test/core/program/build-riscv-tests
 - mkdir -p build
 - cd build

script:
 - py.test -n auto --verbose ../src/test
 - ../src/format --diff
