language: python

python:
 - "2.7"

install:
 # Install verilator
 - git clone https://github.com/cornell-brg/verilator-travisci-cache.git
 - tar xfz verilator-travisci-cache/verilator-travis-3.876.tar.gz
 - export VERILATOR_ROOT=${PWD}/verilator-3.876
 - export PATH=${VERILATOR_ROOT}/bin:$PATH
 - export PYMTL_VERILATOR_INCLUDE_DIR=${VERILATOR_ROOT}/include
 - verilator --version
 # Install PyMTL
 - pip -q install git+https://github.com/cornell-brg/pymtl.git
 # Install YAPF formatter
 - pip -q install git+https://github.com/wizard97/yapf.git
 - pip -q install futures
 - pip -q install hypothesis
 - pip list

before_script:
 - mkdir -p build
 - cd build

script:
 - py.test --verbose ../src/test
 - ../src/format --diff
